export const projects = [
  {
    name: 'Farma Hájek',
    slug: 'farmahajek',
    url: 'https://farmahajek.cz',
    href: '/projects/farmahajek',
    year: 2023,
    descriptionEn: 'Family farm',
    descriptionCs: 'Rodinná farma',
    mockup: '/projects/farmahajek/mockup.webp',
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'framer',
      'shadcn',
      'radixui',
      'leaflet',
      'zod',
      'mui',
    ],
    iphone: '/projects/farmahajek/iphone.webp',
    macbook: '/projects/farmahajek/macbook.webp',
    images: ['/projects/farmahajek/1.webp', '/projects/farmahajek/2.webp'],
  },
  {
    name: 'Rozmluv se',
    slug: 'rozmluvse',
    url: 'https://rozmluv.se',
    href: '/projects/rozmluvse',
    year: 2024,
    descriptionEn: 'Language studio',
    descriptionCs: 'Jazykové studio',
    mockup: '/projects/rozmluvse/mockup.webp',
    iphone: '/projects/rozmluvse/iphone.webp',
    macbook: '/projects/rozmluvse/macbook.webp',
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'sanity',
      'typeform',
      'framer',
      'shadcn',
      'radixui',
    ],
    images: [
      '/projects/rozmluvse/1.webp',
      '/projects/rozmluvse/2.webp',
      '/projects/rozmluvse/3.webp',
      '/projects/rozmluvse/4.webp',
      '/projects/rozmluvse/5.webp',
      '/projects/rozmluvse/6.webp',
      '/projects/rozmluvse/7.webp',
    ],
  },

  {
    name: 'Pneuservis Baudyš',
    slug: 'pneuservisbaudys',
    url: 'https://pneuservisbaudys.cz',
    href: '/projects/pneuservisbaudys',
    year: 2022,
    descriptionEn: 'Local tyre workshop',
    descriptionCs: 'Lokální pneuservis',
    mockup: '/projects/pneuservisbaudys/mockup.webp',
    iphone: '/projects/pneuservisbaudys/iphone.webp',
    macbook: '/projects/pneuservisbaudys/macbook.webp',
    technologies: [
      'react',
      'vite',
      'typescript',
      'tailwind',
      'framer',
      'three',
    ],
    images: ['/projects/pneuservisbaudys/1.webp'],
  },
  {
    name: 'Dhiffushi Inn',
    slug: 'dhiffushiinn',
    url: 'https://dhiffushi-inn.vercel.app',
    href: '/projects/dhiffushiinn',
    year: 2024,
    descriptionEn: 'Maldivian guesthouse',
    descriptionCs: 'Maledivský penzion',
    mockup: '/projects/dhiffushiinn/mockup.webp',
    iphone: '/projects/dhiffushiinn/iphone.webp',
    macbook: '/projects/dhiffushiinn/macbook.webp',
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'sanity',
      'framer',
      'shadcn',
      'radixui',
      'zod',
      'leaflet',
      'prisma',
      'mongodb',
    ],
    images: [
      '/projects/dhiffushiinn/1.webp',
      '/projects/dhiffushiinn/2.webp',
      '/projects/dhiffushiinn/3.webp',
      '/projects/dhiffushiinn/4.webp',
      '/projects/dhiffushiinn/5.webp',
    ],
  },
]
