import type { Project } from '@/types/project'

export const projects: Project[] = [
  {
    name: 'Stadioner',
    slug: 'stadioner',
    url: 'https://stadioner.cz',
    github: 'https://github.com/stadioner/stadioner',
    href: '/projects/stadioner',
    year: 2025,
    updatedAt: '2025-11-02',
    descriptionEn:
      'Stadioner is a local brewery in Kout na Šumavě. The website showcases the beer lineup, news and events, interactive venue maps, and a drinks configurator. It is multilingual, includes a newsletter, subtle animations, CMS-driven content, and cookie compliance.',
    descriptionCs:
      'Stadioner je lokální pivovar v Koutě na Šumavě. Web představuje nabídku piv, novinky a akce, interaktivní mapy provozoven a konfigurátor nápojů. Je vícejazyčný, obsahuje newsletter, jemné animace, správu obsahu přes CMS a respektuje cookies.',
    descriptionEs:
      'Stadioner es una cervecería local en Kout na Šumavě. El sitio presenta la oferta de cervezas, noticias y eventos, mapas interactivos de ubicaciones y un configurador de bebidas. Es multilingüe, incluye newsletter, animaciones sutiles, contenido gestionado por CMS y cumplimiento de cookies.',
    mockup: '/projects/stadioner/mockup.webp',
    iphone: '/projects/stadioner/iphone.webp',
    macbook: '/projects/stadioner/macbook.webp',
    featuresCs: [
      'Interaktivní mapy',
      'Konfigurátor nápojů',
      'Několik Jazyků',
      'Newsletter',
      'Animace',
      'Cookies',
      'CMS',
    ],
    featuresEn: [
      'Interactive maps',
      'Drinks configurator',
      'Multiple languages',
      'Newsletter',
      'Animations',
      'Cookies',
      'CMS',
    ],
    featuresEs: [
      'Mapas interactivos',
      'Configurador de bebidas',
      'Varios idiomas',
      'Newsletter',
      'Animaciones',
      'Cookies',
      'CMS',
    ],
    badgesCs: ['design', 'vývoj'],
    badgesEn: ['design', 'development'],
    badgesEs: ['diseño', 'desarrollo'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'shadcn',
      'radixui',
      'sanity',
      'leaflet',
    ],
    seo: {
      primaryKeyword: 'multilingual brewery website',
      secondaryKeywords: [
        'next.js brewery web development',
        'interactive map website',
        'cms website implementation',
      ],
    },
    images: [
      '/projects/stadioner/1.webp',
      '/projects/stadioner/2.webp',
      '/projects/stadioner/3.webp',
      '/projects/stadioner/4.webp',
    ],
  },
  {
    name: 'My Ride',
    slug: 'myride',
    url: 'https://myride.top',
    github: 'https://github.com/myride-top/myride',
    href: '/projects/myride',
    year: 2025,
    updatedAt: '2025-10-15',
    descriptionEn:
      'My Ride is a community for car enthusiasts to showcase their cars and builds. Create your garage, post updates and mods, track maintenance, and follow other rides.',
    descriptionCs:
      'My Ride je komunita pro automobilové nadšence k prezentaci aut a projektů. Vytvořte si garáž, sdílejte updaty a úpravy, sledujte údržbu a sledujte ostatní vozy.',
    descriptionEs:
      'My Ride es una comunidad para entusiastas del automóvil donde pueden mostrar sus coches y proyectos. Crea tu garaje, publica novedades y modificaciones, registra el mantenimiento y sigue otros vehículos.',
    mockup: '/projects/myride/mockup.webp',
    iphone: '/projects/myride/iphone.webp',
    macbook: '/projects/myride/macbook.webp',
    featuresCs: [
      'Uživatelské profily',
      'Garáž vozidel',
      'Příspěvky a komentáře',
      'Lajky',
      'Nahrávání obrázků',
      'Autentizace',
    ],
    featuresEn: [
      'User profiles',
      'Car garage',
      'Posts and comments',
      'Likes',
      'Image uploads',
      'Authentication',
    ],
    featuresEs: [
      'Perfiles de usuario',
      'Garaje de coches',
      'Publicaciones y comentarios',
      'Me gusta',
      'Subida de imágenes',
      'Autenticación',
    ],
    badgesCs: ['design', 'vývoj'],
    badgesEn: ['design', 'development'],
    badgesEs: ['diseño', 'desarrollo'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'shadcn',
      'radixui',
      'zod',
      'framer',
      'supabase',
      'uploadThing',
      'prisma',
    ],
    seo: {
      primaryKeyword: 'community web application',
      secondaryKeywords: [
        'supabase social platform',
        'next.js app development',
        'fullstack product development',
      ],
    },
    images: [
      '/projects/myride/1.webp',
      '/projects/myride/2.webp',
      '/projects/myride/3.webp',
    ],
  },
  {
    name: 'Flora',
    slug: 'flora',
    url: 'https://flora-interactive.vercel.app',
    github: 'https://github.com/baudys/flora-interactive',
    href: '/projects/flora',
    year: 2025,
    updatedAt: '2025-09-09',
    descriptionEn:
      'The Flora Interactive website features a unique interactive 3D world and a fully functional shopping cart. The project merges cutting-edge technology with attractive visual design, providing users with an engaging and seamless shopping experience.',
    descriptionCs:
      'Webová stránka Flora Interactive nabízí unikátní interaktivní 3D svět, který zajišťuje poutavý uživatelský zážitek. Součástí je také plně funkční nákupní košík, který umožňuje snadné a intuitivní nakupování. Projekt kombinuje moderní technologie s atraktivním vizuálním zpracováním.',
    descriptionEs:
      'El sitio Flora Interactive ofrece un mundo 3D interactivo único y un carrito de compra totalmente funcional. El proyecto combina tecnología moderna con un diseño visual atractivo para ofrecer una experiencia de compra fluida e inmersiva.',
    mockup: '/projects/flora/mockup.webp',
    featuresCs: ['Interaktivní 3D Svět', 'Nákupní Košík'],
    featuresEn: ['Interactive 3D World', 'Shopping Cart'],
    featuresEs: ['Mundo 3D interactivo', 'Carrito de compra'],
    badgesCs: ['design', 'vývoj'],
    badgesEn: ['design', 'development'],
    badgesEs: ['diseño', 'desarrollo'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'framer',
      'shadcn',
      'radixui',
    ],
    seo: {
      primaryKeyword: 'interactive 3d ecommerce website',
      secondaryKeywords: [
        'threejs inspired product showcase',
        'next.js ecommerce experience',
        'framer motion ui interactions',
      ],
    },
    iphone: '/projects/flora/iphone.webp',
    macbook: '/projects/flora/macbook.webp',
    images: [
      '/projects/flora/1.webp',
      '/projects/flora/2.webp',
      '/projects/flora/3.webp',
      '/projects/flora/4.webp',
    ],
  },
  {
    name: 'EasyMarket',
    slug: 'easymarket',
    url: '-',
    href: '/projects/easymarket',
    year: 2025,
    updatedAt: '2025-08-18',
    descriptionEn:
      'EasyMarket is a tool designed to boost sales by automatically renewing listings on major online marketplaces. It features user accounts, sorting options, statistics, and a compact mode. Built with modern technologies, it provides an efficient solution for maximizing listing visibility and performance.',
    descriptionCs:
      'EasyMarket je nástroj určený ke zvýšení prodejů prostřednictvím automatizovaného obnovování inzerátů na velkých online tržištích. Nabízí uživatelské účty, možnosti řazení, statistiky a kompaktní režim. Projekt je postaven na moderních technologiích a poskytuje efektivní řešení pro optimalizaci viditelnosti a výkonu inzerátů.',
    descriptionEs:
      'EasyMarket es una herramienta diseñada para aumentar las ventas renovando automáticamente anuncios en grandes marketplaces. Incluye cuentas de usuario, opciones de ordenación, estadísticas y modo compacto. Construido con tecnologías modernas, ofrece una solución eficiente para mejorar visibilidad y rendimiento.',
    mockup: '/projects/easymarket/mockup.webp',
    featuresCs: [
      'Uživatelské Účty',
      'Možnosti Řazení',
      'Statistika',
      'Kompaktní Režim',
    ],
    featuresEn: [
      'User Accounts',
      'Sorting Options',
      'Statistics',
      'Compact Mode',
    ],
    featuresEs: [
      'Cuentas de usuario',
      'Opciones de ordenación',
      'Estadísticas',
      'Modo compacto',
    ],
    badgesCs: ['design', 'vývoj'],
    badgesEn: ['design', 'development'],
    badgesEs: ['diseño', 'desarrollo'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'framer',
      'shadcn',
      'radixui',
      'zod',
      'clerk',
      'uploadThing',
      'mongodb',
      'prisma',
      'selenium',
    ],
    seo: {
      primaryKeyword: 'marketplace automation platform',
      secondaryKeywords: [
        'listing renewal automation',
        'next.js business application',
        'saas workflow automation',
      ],
    },
    iphone: '/projects/easymarket/iphone.webp',
    macbook: '/projects/easymarket/macbook.webp',
    images: [
      '/projects/easymarket/1.webp',
      '/projects/easymarket/2.webp',
      '/projects/easymarket/3.webp',
    ],
  },
  {
    name: 'Rozmluv se',
    slug: 'rozmluvse',
    url: 'https://rozmluv.se',
    github: 'https://github.com/baudys/rozmluvse',
    href: '/projects/rozmluvse',
    year: 2024,
    updatedAt: '2024-10-12',
    descriptionEn:
      'The Rozmluv.se website is a modern presentation focused on language education. It includes a CMS for easy content management, a blog, a newsletter, support for multiple languages and forms for contact or registration. Thanks to its clear design and practical features, it offers a pleasant user experience and effective communication with visitors.',
    descriptionCs:
      'Webová stránka Rozmluv.se je moderní prezentací zaměřenou na jazykové vzdělávání. Obsahuje CMS pro snadnou správu obsahu, blog, newsletter, podporu více jazyků a formuláře pro kontakt či registraci. Díky přehlednému designu a praktickým funkcím nabízí příjemný uživatelský zážitek a efektivní komunikaci s návštěvníky.',
    descriptionEs:
      'El sitio Rozmluv.se es una presentación moderna enfocada en la enseñanza de idiomas. Incluye un CMS para gestión de contenido, blog, newsletter, soporte multilingüe y formularios de contacto o registro. Gracias a su diseño claro y funciones prácticas ofrece una experiencia agradable y comunicación efectiva.',
    mockup: '/projects/rozmluvse/mockup.webp',
    iphone: '/projects/rozmluvse/iphone.webp',
    macbook: '/projects/rozmluvse/macbook.webp',
    featuresCs: ['CMS', 'Blog', 'Newsletter', 'Několik Jazyků', 'Formuláře'],
    featuresEn: ['CMS', 'Blog', 'Newsletter', 'Multiple Languages', 'Forms'],
    featuresEs: ['CMS', 'Blog', 'Newsletter', 'Varios idiomas', 'Formularios'],
    badgesCs: ['vývoj'],
    badgesEn: ['development'],
    badgesEs: ['desarrollo'],
    creditsCs: {
      label: 'design od',
      action: '@matousmartak',
      href: 'https://matousmartak.com/',
    },
    creditsEn: {
      label: 'design by',
      action: '@matousmartak',
      href: 'https://matousmartak.com/',
    },
    creditsEs: {
      label: 'diseño por',
      action: '@matousmartak',
      href: 'https://matousmartak.com/',
    },
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'sanity',
      'typeform',
      'framer',
      'shadcn',
      'radixui',
    ],
    seo: {
      primaryKeyword: 'language school website development',
      secondaryKeywords: [
        'multilingual educational website',
        'cms and newsletter integration',
        'conversion-focused service website',
      ],
    },
    images: [
      '/projects/rozmluvse/1.webp',
      '/projects/rozmluvse/2.webp',
      '/projects/rozmluvse/3.webp',
      '/projects/rozmluvse/4.webp',
      '/projects/rozmluvse/5.webp',
      '/projects/rozmluvse/6.webp',
      '/projects/rozmluvse/7.webp',
    ],
  },
  {
    name: 'Zabi',
    slug: 'zabi',
    url: 'https://polyuretanzabi.cz',
    href: '/projects/zabi',
    year: 2025,
    updatedAt: '2025-06-20',
    descriptionEn:
      'Manufacturing and renovation of polyurethane parts for industrial use, including wheels, rollers, shafts, and custom components.',
    descriptionCs:
      'Výroba a renovace polyuretanových dílů pro průmyslové využití, včetně kol, válečků, hřídelí a zakázkových komponentů.',
    descriptionEs:
      'Fabricación y renovación de piezas de poliuretano para uso industrial, incluyendo ruedas, rodillos, ejes y componentes a medida.',
    mockup: '/projects/zabi/mockup.webp',
    iphone: '/projects/zabi/iphone.webp',
    macbook: '/projects/zabi/macbook.webp',
    featuresCs: ['Interakce'],
    featuresEn: ['Interactions'],
    featuresEs: ['Interacciones'],
    badgesCs: ['vývoj'],
    badgesEn: ['development'],
    badgesEs: ['desarrollo'],
    creditsCs: {
      label: 'design od',
      action: '@matousmartak',
      href: 'https://matousmartak.com/',
    },
    creditsEn: {
      label: 'design by',
      action: '@matousmartak',
      href: 'https://matousmartak.com/',
    },
    creditsEs: {
      label: 'diseño por',
      action: '@matousmartak',
      href: 'https://matousmartak.com/',
    },
    technologies: ['nextjs', 'typescript', 'tailwind', 'shadcn', 'radixui'],
    seo: {
      primaryKeyword: 'industrial manufacturing website',
      secondaryKeywords: [
        'b2b website redesign',
        'lead generation landing page',
        'tailwind production website',
      ],
    },
    images: [
      '/projects/zabi/1.webp',
      '/projects/zabi/2.webp',
      '/projects/zabi/3.webp',
    ],
  },
  {
    name: 'Dhiffushi Inn',
    slug: 'dhiffushiinn',
    url: 'https://dhiffushi-inn.com',
    github: 'https://github.com/baudys/dhiffushi-inn',
    href: '/projects/dhiffushiinn',
    year: 2024,
    updatedAt: '2024-09-28',
    descriptionEn:
      'The website for Dhiffushi Inn combines a CMS, a booking engine, database connectivity, multi-language support, intuitive forms and an interactive map. The design is responsive and user-friendly, focusing on speed and ease of management. The project provides a modern and functional hotel presentation with an emphasis on visitor convenience.',
    descriptionCs:
      'Webová stránka pro Dhiffushi Inn spojuje CMS, rezervační systém, databázové napojení, podporu více jazyků, intuitivní formuláře a interaktivní mapu. Design je responzivní a uživatelsky přívětivý, zaměřený na rychlost a jednoduchou správu. Projekt zajišťuje moderní a funkční prezentaci hotelu s důrazem na pohodlí návštěvníků.',
    descriptionEs:
      'El sitio de Dhiffushi Inn combina CMS, motor de reservas, conexión a base de datos, soporte multilingüe, formularios intuitivos y mapa interactivo. El diseño es responsive y fácil de usar, orientado a velocidad y gestión simple. El resultado es una presentación hotelera moderna y funcional centrada en la comodidad del visitante.',
    mockup: '/projects/dhiffushiinn/mockup.webp',
    iphone: '/projects/dhiffushiinn/iphone.webp',
    macbook: '/projects/dhiffushiinn/macbook.webp',
    featuresCs: [
      'CMS',
      'Booking Systém',
      'Napojení na Databázi',
      'Několik Jazyků',
      'Formuláře',
      'Vlastní Mapa',
      'Galerie',
    ],
    featuresEn: [
      'CMS',
      'Booking System',
      'Database Connection',
      'Multiple Languages',
      'Forms',
      'Custom Map',
      'Gallery',
    ],
    featuresEs: [
      'CMS',
      'Sistema de reservas',
      'Conexión a base de datos',
      'Varios idiomas',
      'Formularios',
      'Mapa personalizado',
      'Galería',
    ],
    badgesCs: ['design', 'vývoj'],
    badgesEn: ['design', 'development'],
    badgesEs: ['diseño', 'desarrollo'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'sanity',
      'framer',
      'shadcn',
      'radixui',
      'zod',
      'leaflet',
      'prisma',
      'mongodb',
    ],
    seo: {
      primaryKeyword: 'hotel booking website development',
      secondaryKeywords: [
        'multilingual hospitality website',
        'booking engine integration',
        'travel website with cms',
      ],
    },
    images: [
      '/projects/dhiffushiinn/1.webp',
      '/projects/dhiffushiinn/2.webp',
      '/projects/dhiffushiinn/3.webp',
      '/projects/dhiffushiinn/4.webp',
      '/projects/dhiffushiinn/5.webp',
    ],
  },
  {
    name: 'Grössl',
    slug: 'grossl',
    url: 'https://dominikgrossl.com',
    href: '/projects/grossl',
    year: 2024,
    updatedAt: '2024-07-14',
    descriptionEn:
      'The Dominik Grossl website is a modern and visually engaging presentation that stands out with complex animations. These animations create a dynamic and interactive experience that highlights the creativity and technological maturity of the project. The design is designed with attention to detail, aesthetics and smooth user navigation.',
    descriptionCs:
      'Webová stránka Dominik Grossl je moderní a vizuálně poutavá prezentace, která vyniká komplexními animacemi. Tyto animace vytvářejí dynamický a interaktivní zážitek, který zdůrazňuje kreativitu a technologickou vyspělost projektu. Design je navržen s důrazem na detail, estetičnost a plynulou uživatelskou navigaci.',
    descriptionEs:
      'El sitio de Dominik Grossl es una presentación moderna y visualmente atractiva que destaca por animaciones complejas. Estas animaciones generan una experiencia dinámica e interactiva que resalta la creatividad y madurez tecnológica del proyecto. El diseño está cuidado al detalle, con enfoque estético y navegación fluida.',
    mockup: '/projects/grossl/mockup.webp',
    iphone: '/projects/grossl/iphone.webp',
    macbook: '/projects/grossl/macbook.webp',
    featuresCs: ['Komplexní Animace'],
    featuresEn: ['Complex Animations'],
    featuresEs: ['Animaciones complejas'],
    badgesCs: ['design', 'vývoj'],
    badgesEn: ['design', 'development'],
    badgesEs: ['diseño', 'desarrollo'],
    technologies: ['nextjs', 'typescript', 'tailwind', 'framer'],
    seo: {
      primaryKeyword: 'animation rich portfolio website',
      secondaryKeywords: [
        'framer motion web animations',
        'creative developer portfolio',
        'high-end landing page build',
      ],
    },
    images: [],
  },
]
