export const projects = [
  {
    name: 'Flora',
    slug: 'flora',
    url: 'https://flora-interactive.vercel.app',
    href: '/projects/flora',
    year: 2025,
    descriptionEn:
      'The Flora Interactive website features a unique interactive 3D world and a fully functional shopping cart. The project merges cutting-edge technology with attractive visual design, providing users with an engaging and seamless shopping experience.',
    descriptionCs:
      'Webová stránka Flora Interactive nabízí unikátní interaktivní 3D svět, který zajišťuje poutavý uživatelský zážitek. Součástí je také plně funkční nákupní košík, který umožňuje snadné a intuitivní nakupování. Projekt kombinuje moderní technologie s atraktivním vizuálním zpracováním.',
    mockup: '/projects/flora/mockup.webp',
    featuresCs: ['Interaktivní 3D Svět', 'Nákupní Košík'],
    featuresEn: ['Interactive 3D World', 'Shopping Cart'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'framer',
      'shadcn',
      'radixui',
    ],
    iphone: '/projects/flora/iphone.webp',
    macbook: '/projects/flora/macbook.webp',
    images: [
      '/projects/flora/1.webp',
      '/projects/flora/2.webp',
      '/projects/flora/3.webp',
      '/projects/flora/4.webp',
    ],
  },
  {
    name: 'EasyMarket',
    slug: 'easymarket',
    url: '',
    href: '/projects/easymarket',
    year: 2025,
    descriptionEn:
      'EasyMarket is a tool designed to boost sales by automatically renewing listings on major online marketplaces. It features user accounts, sorting options, statistics, and a compact mode. Built with modern technologies, it provides an efficient solution for maximizing listing visibility and performance.',
    descriptionCs:
      'EasyMarket je nástroj určený ke zvýšení prodejů prostřednictvím automatizovaného obnovování inzerátů na velkých online tržištích. Nabízí uživatelské účty, možnosti řazení, statistiky a kompaktní režim. Projekt je postaven na moderních technologiích a poskytuje efektivní řešení pro optimalizaci viditelnosti a výkonu inzerátů.',
    mockup: '/projects/easymarket/mockup.webp',
    featuresCs: [
      'Uživatelské Účty',
      'Možnosti Řazení',
      'Statistika',
      'Kompaktní Režim',
    ],
    featuresEn: [
      'User Accounts',
      'Sorting Options',
      'Statistics',
      'Compact Mode',
    ],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'framer',
      'shadcn',
      'radixui',
      'zod',
      'clerk',
      'uploadThing',
      'mongodb',
      'prisma',
      'selenium',
    ],
    iphone: '/projects/easymarket/iphone.webp',
    macbook: '/projects/easymarket/macbook.webp',
    images: [
      '/projects/easymarket/1.webp',
      '/projects/easymarket/2.webp',
      '/projects/easymarket/3.webp',
    ],
  },
  {
    name: 'Farma Hájek',
    slug: 'farmahajek',
    url: 'https://farmahajek.cz',
    href: '/projects/farmahajek',
    year: 2023,
    descriptionEn:
      'The Hájek Farm website is designed as a modern presentation of the farm and its activities. It includes a blog with the latest news, a newsletter for regular information, its own interactive map and an overview gallery. Thanks to its functional design and user-friendly interface, it ensures easy communication and clear presentation of the farm to visitors.',
    descriptionCs:
      'Webová stránka Farma Hájek je navržena jako moderní prezentace farmy a jejích aktivit. Obsahuje blog s aktuálními novinkami, newsletter pro pravidelné informace, vlastní interaktivní mapu a přehlednou galerii. Díky funkčnímu designu a uživatelsky přívětivému rozhraní zajišťuje snadnou komunikaci a přehledné představení farmy návštěvníkům.',
    mockup: '/projects/farmahajek/mockup.webp',
    featuresCs: ['Blog', 'Newsletter', 'Vlastní Mapa', 'Galerie'],
    featuresEn: ['Blog', 'Newsletter', 'Custom Map', 'Gallery'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'framer',
      'shadcn',
      'radixui',
      'leaflet',
      'zod',
      'mui',
    ],
    iphone: '/projects/farmahajek/iphone.webp',
    macbook: '/projects/farmahajek/macbook.webp',
    images: ['/projects/farmahajek/1.webp', '/projects/farmahajek/2.webp'],
  },
  {
    name: 'Rozmluv se',
    slug: 'rozmluvse',
    url: 'https://rozmluv.se',
    href: '/projects/rozmluvse',
    year: 2024,
    descriptionEn:
      'The Rozmluv.se website is a modern presentation focused on language education. It includes a CMS for easy content management, a blog, a newsletter, support for multiple languages and forms for contact or registration. Thanks to its clear design and practical features, it offers a pleasant user experience and effective communication with visitors.',
    descriptionCs:
      'Webová stránka Rozmluv.se je moderní prezentací zaměřenou na jazykové vzdělávání. Obsahuje CMS pro snadnou správu obsahu, blog, newsletter, podporu více jazyků a formuláře pro kontakt či registraci. Díky přehlednému designu a praktickým funkcím nabízí příjemný uživatelský zážitek a efektivní komunikaci s návštěvníky.',
    mockup: '/projects/rozmluvse/mockup.webp',
    iphone: '/projects/rozmluvse/iphone.webp',
    macbook: '/projects/rozmluvse/macbook.webp',
    featuresCs: ['CMS', 'Blog', 'Newsletter', 'Několik Jazyků', 'Formuláře'],
    featuresEn: ['CMS', 'Blog', 'Newsletter', 'Multiple Languages', 'Forms'],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'sanity',
      'typeform',
      'framer',
      'shadcn',
      'radixui',
    ],
    images: [
      '/projects/rozmluvse/1.webp',
      '/projects/rozmluvse/2.webp',
      '/projects/rozmluvse/3.webp',
      '/projects/rozmluvse/4.webp',
      '/projects/rozmluvse/5.webp',
      '/projects/rozmluvse/6.webp',
      '/projects/rozmluvse/7.webp',
    ],
  },

  {
    name: 'Pneuservis Baudyš',
    slug: 'pneuservisbaudys',
    url: 'https://pneuservisbaudys.cz',
    href: '/projects/pneuservisbaudys',
    year: 2022,
    descriptionEn:
      "The website for Pneuservis Baudyš was created with an emphasis on modern design and functionality. It includes interactive 3D models and an integrated Google Map for easy customer orientation. The project combines aesthetics, technology and user-friendliness to effectively present the tire shop's services and facilitate communication with customers.",
    descriptionCs:
      'Webová stránka pro Pneuservis Baudyš byla vytvořena s důrazem na moderní design a funkčnost. Obsahuje interaktivní 3D modely a integrovanou Google Mapu pro snadnou orientaci zákazníků. Projekt kombinuje estetiku, technologie a uživatelskou přívětivost, aby efektivně prezentoval služby pneuservisu a usnadnil komunikaci se zákazníky.',
    mockup: '/projects/pneuservisbaudys/mockup.webp',
    iphone: '/projects/pneuservisbaudys/iphone.webp',
    macbook: '/projects/pneuservisbaudys/macbook.webp',
    featuresCs: ['3D Modely', 'Google Mapa'],
    featuresEn: ['3D Model', 'Google Map'],
    technologies: [
      'react',
      'vite',
      'typescript',
      'tailwind',
      'framer',
      'three',
    ],
    images: ['/projects/pneuservisbaudys/1.webp'],
  },
  {
    name: 'Dhiffushi Inn',
    slug: 'dhiffushiinn',
    url: 'https://dhiffushi-inn.com',
    href: '/projects/dhiffushiinn',
    year: 2024,
    descriptionEn:
      'The website for Dhiffushi Inn combines a CMS, a booking engine, database connectivity, multi-language support, intuitive forms and an interactive map. The design is responsive and user-friendly, focusing on speed and ease of management. The project provides a modern and functional hotel presentation with an emphasis on visitor convenience.',
    descriptionCs:
      'Webová stránka pro Dhiffushi Inn spojuje CMS, rezervační systém, databázové napojení, podporu více jazyků, intuitivní formuláře a interaktivní mapu. Design je responzivní a uživatelsky přívětivý, zaměřený na rychlost a jednoduchou správu. Projekt zajišťuje moderní a funkční prezentaci hotelu s důrazem na pohodlí návštěvníků.',
    mockup: '/projects/dhiffushiinn/mockup.webp',
    iphone: '/projects/dhiffushiinn/iphone.webp',
    macbook: '/projects/dhiffushiinn/macbook.webp',
    featuresCs: [
      'CMS',
      'Booking Systém',
      'Napojení na Databázi',
      'Několik Jazyků',
      'Formuláře',
      'Vlastní Mapa',
      'Galerie',
    ],
    featuresEn: [
      'CMS',
      'Booking System',
      'Database Connection',
      'Multiple Languages',
      'Forms',
      'Custom Map',
      'Gallery',
    ],
    technologies: [
      'nextjs',
      'typescript',
      'tailwind',
      'sanity',
      'framer',
      'shadcn',
      'radixui',
      'zod',
      'leaflet',
      'prisma',
      'mongodb',
    ],
    images: [
      '/projects/dhiffushiinn/1.webp',
      '/projects/dhiffushiinn/2.webp',
      '/projects/dhiffushiinn/3.webp',
      '/projects/dhiffushiinn/4.webp',
      '/projects/dhiffushiinn/5.webp',
    ],
  },
  {
    name: 'Smart Form',
    slug: 'smartform',
    url: 'https://smart-formular.netlify.app/',
    href: '/projects/smartform',
    year: 2023,
    descriptionEn:
      'The Smart Form website is designed for efficient data and form management. It offers automatic completion of data by ID number, connection to a database for reliable storage of information and intuitive forms. Thanks to modern technologies and a simple interface, it ensures fast and easy data handling.',
    descriptionCs:
      'Webová stránka Smart Formulář je vytvořena pro efektivní správu dat a formulářů. Nabízí automatické doplnění údajů podle IČO, napojení na databázi pro spolehlivé ukládání informací a intuitivní formuláře. Díky moderním technologiím a jednoduchému rozhraní zajišťuje rychlou a snadnou práci s daty.',
    mockup: '/projects/smartform/mockup.webp',
    iphone: '/projects/smartform/iphone.webp',
    macbook: '/projects/smartform/macbook.webp',
    featuresCs: [
      'Automatické Doplnění Údajů Podle IČO',
      'Napojení na Databázi',
      'Formuláře',
    ],
    featuresEn: ['Autocomplete Based on IČO', 'Database Connection', 'Forms'],
    technologies: ['nextjs', 'tailwind', 'mongodb', 'mui'],
    images: [],
  },
  {
    name: 'Grössl',
    slug: 'grossl',
    url: 'https://dominikgrossl.com',
    href: '/projects/grossl',
    year: 2024,
    descriptionEn:
      'The Dominik Grossl website is a modern and visually engaging presentation that stands out with complex animations. These animations create a dynamic and interactive experience that highlights the creativity and technological maturity of the project. The design is designed with attention to detail, aesthetics and smooth user navigation.',
    descriptionCs:
      'Webová stránka Dominik Grossl je moderní a vizuálně poutavá prezentace, která vyniká komplexními animacemi. Tyto animace vytvářejí dynamický a interaktivní zážitek, který zdůrazňuje kreativitu a technologickou vyspělost projektu. Design je navržen s důrazem na detail, estetičnost a plynulou uživatelskou navigaci.',
    mockup: '/projects/grossl/mockup.webp',
    iphone: '/projects/grossl/iphone.webp',
    macbook: '/projects/grossl/macbook.webp',
    featuresCs: ['Komplexní Animace'],
    featuresEn: ['Complex Animations'],
    technologies: ['nextjs', 'typescript', 'tailwind', 'framer'],
    images: [],
  },
]
